"""empty message

Revision ID: 0ebd94cae9a1
Revises: 
Create Date: 2021-12-03 15:26:31.686247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ebd94cae9a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=8), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashiers_employee_id'), 'cashiers', ['employee_id'], unique=True)
    op.create_table('chef',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=8), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chef_employee_id'), 'chef', ['employee_id'], unique=True)
    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=8), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managers_employee_id'), 'managers', ['employee_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managers_employee_id'), table_name='managers')
    op.drop_table('managers')
    op.drop_index(op.f('ix_chef_employee_id'), table_name='chef')
    op.drop_table('chef')
    op.drop_index(op.f('ix_cashiers_employee_id'), table_name='cashiers')
    op.drop_table('cashiers')
    # ### end Alembic commands ###
